version: '3'
services:
  db:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pillar
      - POSTGRES_USER=my_butt
      - POSTGRES_PASSWORD=my_ass
  app:
    build: .
    image: bengershuny/node-app:10
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: ['yarn', 'start']
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - PORT=4000
      - NODE_ENV=development
      - DATABASE_URL=postgres://my_butt:my_ass@db:5432/pillar
    links:
      - db
volumes:
  postgres:
